### ISSUE TITLE
User Story - Manual Steering

### ISSUE THREAD

**Issue by JakobRoseke** [DIT112-V20/group-05#2]
As a skeptic of technology, I want to be able to steer the car myself, so that I don't have to trust the car to do it for me.

Commits;
[fa3cc91547a7fa1d00b04930ed074c7e9f6f0260](https://github.com/DIT112-V20/group-05/commit/fa3cc91547a7fa1d00b04930ed074c7e9f6f0260)
[8b9f0c8cf9e712c002b399e4f520d1c7658cc86a](https://github.com/DIT112-V20/group-05/commit/8b9f0c8cf9e712c002b399e4f520d1c7658cc86a)

**Comment by Hallberg-eric** [comment]
As a user I want to be able to turn the car on/off, so that i can control the car

**Comment by Hallberg-eric** [comment]
As a user, I want to be able to set the speed in real time, so that i can control the car

**Comment by Hallberg-eric** [comment]
As a user, i want the car to be able to break, so that i can stop the car.

**Comment by Hallberg-eric** [comment]
As a user, I want to be able to reverse the car, so that I can move the car if stuck in a bad position
