### ISSUE TITLE
Car needs a push

### ISSUE THREAD

**Issue by JakobRoseke** [DIT112-V20/group-05#25]
Right now the speed of the car gets increment at 0.3m/s. However, most of the time, it needs a very slight push for it to start moving.

My theory is that the speed begins at such low speed that the motors don't really start up on their own and need some exterior force to get going.

Would you say that it is bad for the car/motors to begin at such low speed and giving it a nudge, the speed could be changed to somewhat higher. However, I wouldn't want the car to accelerate into the next millennia in the beginning...

**Comment by platisd** [comment]
Can you share the code you're using?

**Comment by JakobRoseke** [comment]
https://github.com/DIT112-V20/group-05/blob/FixingMovementIssues/stopBeforeObstacle/stopBeforeObstacle.ino

From line 52 is where the incrementing methods begins.

**Comment by platisd** [comment]
To begin with you have an unrelated problem [here](https://github.com/DIT112-V20/group-05/blob/FixingMovementIssues/stopBeforeObstacle/stopBeforeObstacle.ino#L102). You may have even received some feedback on this during the first assignment.

Other than that, what is the **exact** behavior you see? Will the car eventually start moving after a while or will the car never start moving at all?
(I assume that in both cases you are powering it up with batteries and they are sufficiently charged)

**Comment by JakobRoseke** [comment]
1. The problem is something I recognized, haven't gotten to fix it yet. We are gonna look at that method, it might very well change.

2. So, from it standing still, the car doesn't move at all. It will sometimes start to move if I increment the speed enough, but most of the times I have to push the car slightly.

**Comment by platisd** [comment]
> 2\. So, from it standing still, the car doesn't move at all. It will sometimes start to move if I increment the speed enough, but most of the times I have to push the car slightly.

This is **very** strange (almost impossible/unexplainable if I may add) since if you are in the "cruise control" mode **the power to the motors will keep increasing** until the target speed is reached.

Try [this sketch](https://github.com/platisd/smartcar_shield/blob/master/examples/Car/DistanceCar/DistanceCar.ino) with a low speed, e.g. 0.3. What happens then?
In my case, I can even make the car move at 0.1 m/sec etc.

**Comment by JakobRoseke** [comment]
The sketch worked at 0.3 m/s, however; during group meeting 27th of April, we concluded that the issue probably is the speed "isn't there" on our regular sketch.

I will close the issue and either find a fix or let it be the way it is.
