### ISSUE TITLE
Images not there after merge.

### ISSUE THREAD

**Issue by JakobRoseke** [DIT112-V20/group-05#29]
After I merge the images from the app prototype they no longer show up. I don't know what happened, it seems that the file is a text file that is completely empty. You might have to add the images as PNG-files, I suggest to add them inside a folder in the root.

**Comment by razgoth** [comment]
It might be a silly question but when you say  "inside a folder in the root." what does that mean ?

**Comment by JakobRoseke** [comment]
> It might be a silly question but when you say "inside a folder in the root." what does that mean ?

Basically where you cloned the repository, where you already have the app prototype images. But instead, have a folder with the images as PNG/JPG or whatever type.

The root is basically the "first" folder of the directory. So the root for the repository would be the group-05 folder that you cloned.

**Comment by razgoth** [comment]
I think I get it now, I created a branch called images and now asked for a pull request
