### ISSUE TITLE
The .c and .h file gives a lot of errors

### ISSUE THREAD

**Issue by JakobRoseke** [DIT112-V20/group-05#41]
We have created a webserver for the car now. It worked perfectly fine when it was its own .ino file. However, when I was going to add it to our current file I wanted to have it as a .c and a .h file as such to not make a mess of the .ino file.

This caused a lot of errors...
What I did was, make them .c and .h -> added the, from what I understood, correct lines of code to .h file -> #include "Webserver.h" and there it went...

The files are in src/smartCar

**Comment by platisd** [comment]
Show us some code please.

**Comment by JakobRoseke** [comment]
Ahh..  there aren't in the master branch.
Instead of posting all code raw, I will post the URL to the files;
https://github.com/DIT112-V20/group-05/tree/webserver/src/smartCar

**Comment by platisd** [comment]
You can apply the following [patch](https://github.com/DIT112-V20/group-05/files/4563265/0001-Fix-compilation-errors.patch.txt) by placing it in your repository and then running `git am 0001-Fix-compilation-errors.patch.txt`.

There were several problems with it. Overall, you could have kept it simple and moved your code to another `.ino` file. Then you wouldn't even need to include anything extra, the IDE would find automatically those files and include them for you.

You can have a look into the changes in the patch but to summarize them as "dont's":
* Don't use C files if you are writing in C++. The C compiler does not know what a `class` is (along with many other things from C++).
* Don't expose things you don't want exposed via a header file.
* Don't redefine variables
* Don't use global variables if you don't need to, especially if they are not constant.

**Comment by JakobRoseke** [comment]
Alright! Thank you so much!
There are so many things you can do with Git, it really is incredible.
