### ISSUE TITLE
Suggestion: Place all the android files in a 'Android' folder

### ISSUE THREAD

**Issue by JakobRoseke** [DIT112-V20/group-05#55]
Currently, on the master branch, we have all of the, what I presume are, android-studio/application files. We should maybe try to place them in one folder as having them all in the root could bring risks.

**Comment by JakobRoseke** [comment]
@razgoth there were also 3 folders, .gradle .idea and gradle/wrapper that should be in the the new folder.

Also what is the UIDesign folder? Is it part of the app or is it a different app?

**Comment by razgoth** [comment]
UI design is our main folder that contains the android app the others will be deleted
